name: Generate Datas

on:
  schedule: # execute every 12 hours
    #- cron: "* */12 * * *"
    - cron: "* * * * *"


  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ernstbeckerneto
          svg_out_path: dist/github-contribution-grid-snake.svg
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-white.svg?palette=github-light
            dist/github-contribution-grid-snake-sissa.svg?color_snake=#ff0043
            dist/github-contribution-grid-snake-sissa-white.svg?color_snake=#ff0043
      
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
